name: Nix Flake Check

on:
  pull_request:
    branches: [ main ] 

jobs:
  flake-check:
    name: Check Nix format with `nix fmt`
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Run nix flake check
        run: nix flake check --show-trace

  stylua-check: 
    name: Check Lua format with `stylua`
    runs-on: utunbu-latest

    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install and run stylua
      uses: JohnnyMorganz/stylua-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: latest
        args: --check .

